# Generated by Django 3.2.4 on 2022-04-19 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usercontactdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactdata',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usercontactdata',
            name='key',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
