# Generated by Django 2.2.14 on 2022-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220419_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
