# Generated by Django 2.2.14 on 2022-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('choice1', models.CharField(blank=True, max_length=100, null=True)),
                ('choice2', models.CharField(blank=True, max_length=100, null=True)),
                ('choice3', models.CharField(blank=True, max_length=100, null=True)),
                ('choice4', models.CharField(blank=True, max_length=100, null=True)),
                ('choices', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=50)),
                ('image', models.ImageField(default='quiz/def_quiz.png', upload_to='quiz')),
            ],
        ),
    ]
