# Generated by Django 2.2.14 on 2022-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='movies.def_movie.png', null=True, upload_to='movies')),
            ],
        ),
    ]
